---
# ============================================================
# SITE MASTER PLAYBOOK – CLEAN + VALIDATED
# ============================================================

# ------------------------------------------------------------
# 1. COMMON BASELINE FOR ALL HOSTS
# ------------------------------------------------------------
- name: Apply common baseline configuration
  hosts: all
  become: yes
  roles:
    - common

# ------------------------------------------------------------
# 2. NTP CONFIGURATION
# ------------------------------------------------------------
- name: Configure NTP server
  hosts: prdx-ntp101
  become: yes
  roles:
    - ntp

- name: Configure NTP clients
  hosts:
    - prdx-nsprimary101
    - prdx-ftp101
    - prdx-nfs101
    - prdx-db101
    - prdx-webserver101
    - prdx-haproxy101
    - prdx-nagios101
    - prdx-dprimary101
    - prdx-dworker101
    - prdx-dworker102
  become: yes
  roles:
    - ntp

# ------------------------------------------------------------
# 3. DNS SERVER (BIND)
# ------------------------------------------------------------
- name: Configure DNS server
  hosts: prdx-nsprimary101
  become: yes
  roles:
    - dns

# ------------------------------------------------------------
# 4. FTP SERVER
# ------------------------------------------------------------
- name: Configure FTP server
  hosts: prdx-ftp101
  become: yes
  roles:
    - ftp

# ------------------------------------------------------------
# 5. NFS CONFIGURATION
# ------------------------------------------------------------
- name: Configure NFS server
  hosts: prdx-nfs101
  become: yes
  tasks:
    - import_role:
        name: nfs
        tasks_from: server.yml

- name: Configure NFS clients
  hosts:
    - prdx-webserver101
    - prdx-haproxy101
    - prdx-db101
    - prdx-dprimary101
    - prdx-dworker101
    - prdx-dworker102
  become: yes
  tasks:
    - import_role:
        name: nfs
        tasks_from: client.yml

# ------------------------------------------------------------
# 6. WEB SERVER (APACHE)
# ------------------------------------------------------------
- name: Configure Web Server
  hosts: prdx-webserver101
  become: yes
  roles:
    - web

# ------------------------------------------------------------
# 7. HAPROXY LOAD BALANCER
# ------------------------------------------------------------
- name: Configure HAProxy
  hosts: prdx-haproxy101
  become: yes
  roles:
    - haproxy

# ------------------------------------------------------------
# 8. DOCKER SWARM
# ------------------------------------------------------------
- name: Configure Docker Swarm Manager
  hosts: prdx-dprimary101
  become: yes
  tasks:
    - import_role:
        name: docker
        tasks_from: manager.yml

- name: Configure Docker Swarm Workers
  hosts:
    - prdx-dworker101
    - prdx-dworker102
  become: yes
  tasks:
    - import_role:
        name: docker
        tasks_from: worker.yml

# ------------------------------------------------------------
# 9. NAGIOS SERVER + NRPE CLIENTS
# ------------------------------------------------------------
- name: Install & Configure Nagios Server
  hosts: prdx-nagios101
  become: yes
  tasks:
    - import_role:
        name: nagios
        tasks_from: install.yml
    - import_role:
        name: nagios
        tasks_from: config.yml

- name: Install NRPE on monitored servers
  hosts:
    - prdx-webserver101
    - prdx-nfs101
    - prdx-ftp101
  become: yes
  tasks:
    - import_role:
        name: nagios
        tasks_from: nrpe.yml
